Repository AY2021S2-CS2113-W10-3/tp, pull requests merged in 2021-03, with the labels that each got.

#23 Add help command
  src/main/java/seedu/duke/Duke.java
Labels: priority.High, type.Story

#38 Add JUnit Test for help command
  src/test/java/seedu/duke/DukeTest.java
Labels: priority.High, type.Task

#39 Add JUnit test for exit
  src/test/java/seedu/duke/DukeTest.java
Labels: priority.High, type.Task

#47 [Sam] add assert to ensure that projectInfo will not be null
  src/main/java/seedu/duke/Duke.java
Labels: priority.High, type.Task

#69 Fix test for Find feature bug
  src/main/java/seedu/duke/Duke.java
  src/test/java/seedu/duke/DukeTest.java
Labels: priority.High, type.Bug

#66 [Sam] Refactor Code
  META-INF/MANIFEST.MF
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Project.java
  src/main/java/seedu/duke/command/CommandHandler.java
  src/main/java/seedu/duke/exception/DukeException.java
  src/main/java/seedu/duke/parser/CommandParser.java
  src/main/java/seedu/duke/parser/InputParser.java
  src/main/java/seedu/duke/resource/ResourceManager.java
  src/main/java/seedu/duke/ui/MainUi.java
  src/test/java/seedu/duke/DukeTest.java
Labels: priority.High

#101 Add find to help
  src/main/java/seedu/duke/ui/MainUi.java
  src/test/java/seedu/duke/DukeTest.java
Labels: priority.High, type.Task
